### ISSUE TITLE
META: brief.mozdev.org open bugs

### ISSUE THREAD

**Issue by tanriol** [tanriol/digest#2]
As of 2013-07-19

Needs testing
- [ ] 23985     brief opens download-dialog for .swf when flash is disabled (found no such feed)
- [ ] 25187     Not cleared the table entries_text_segments
- [ ] 25475 Pressing buttons in the Brief options dialog box causes the dialog box height to increase
- [ ] 25502     Intermittently can't "X" feed if updates in progress (#17?)

Accepted
- [ ] 18662     Relative URLs in articles are made relative to file:// (#9)
- [ ] 19599     Sound notification (#14)
- [ ] 20548     One RSS feed not showing updates (#45)
- [ ] 20697     keybord control of the gui (in the form of #30)
- [ ] 23292     Feeds folder deleted initially - RSS in Nirvana (#36)
- [ ] 23371     Old feed entries are not expiring when past configured age. (#34)
- [ ] 23503     Atom feed's icon does not show up. (#32)
- [ ] 23706     Unwanted article opening when pressing enter in search/adress bars (#19)
- [ ] 23767     Request: add preference to turn off smooth scroll (#37)
- [ ] 24369     date parse - failed using YY for the year (#18)
- [ ] 24527     Feature request: Incoming feeds filtering (megred into #38)
- [ ] 24529     Feature request: Auto mark read (megred into #38)
- [ ] 24627     Pressing [Enter] key in sidebar while Brief is open causes the highlighted feed item to open in a new tab (#19)
- [ ] 24787     One feed doesn't update (#45)
- [ ] 25049     Youtube RSS feeds display in incorrect order (#33)
- [ ] 25140     account managment ? (#3)
- [ ] 25372     suggestions: hide feeds, alternate CSS, etc (megred into #38)
- [ ] 25374     Can't change feed URLs (#16)

Fixed
- [x] 20005     Brief's CSS settings wont save (#15)
- [x] 22736     brief highlight feature after search does not work with accents (#21)
- [x] 24528     Feature request: Visual notification of new feeds (#22)
- [x] 24757     "Mark Read" buttons fail on when sorted oldest first (#17)
- [x] 25060     No Entries shown also are unreaded (#49)
- [x] 25269     feeds update but won't display (#49)
- [x] 25284     marked as incompatible with Firefox 17.0

Irreproducible
- [x] 25297     Brief does not work properly - mixed feeds and news (#49?)
- [x] 25499     RSS BROKEN: wired.com (worksforme)

Invalid, outdated and duplicates
- [x] 20398     google reader synchronization (no Google Reader)
- [x] 21177     TYPO in Spanish translation (absent in Brief 1.7a1/Digest)
- [x] 22434     improving Twitter RSS experience to make Brief a Twitter reader (no Twitter RSS)
- [x] 24928     Search Filtering is Incorrect (notabug)
- [x] 25353     images in some feeds are not show (duplicate of 18662/#9)
- [x] 25408     no pics (duplicate of 18662/#9)
- [x] 25508     BRIEF does not display feeds (duplicate of 25060/#49)
- [x] 25506     Not showing any entries. (duplicate of 25060/#49)
