### ISSUE TITLE
META: improvement suggestions

### ISSUE THREAD

**Issue by tanriol** [tanriol/digest#38]
https://www.mozdev.org/bugs/show_bug.cgi?id=25372
- [ ] better skin support
- [ ] hide feeds with no unread items
- [ ] better support place
- [ ] scroll-to-top / collapse / star buttons on the bottom of an item

https://www.mozdev.org/bugs/show_bug.cgi?id=24529
- [ ] an easy way to mark everything as read

https://www.mozdev.org/bugs/show_bug.cgi?id=24527
- [ ] feed filtering

https://addons.mozilla.org/en-US/firefox/addon/digest/reviews/477508
- [ ] show feeds with unread items only in the feed list
- [ ] control sort order per-feed
- [ ] enhance "auto mark as read"
- [ ] naturalize shortcuts (ex. Space) and/or shortcut customization

https://forums.mozilla.org/addons/viewtopic.php?f=23&t=14582
- [ ] delete all items displayed/in-query ( https://forums.mozilla.org/addons/viewtopic.php?f=23&t=14582&p=29635#p29635 )
